# -*- coding: utf-8 -*-
"""news_crawling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOmN16eTCrUfKyeN6ov3lxFcDA26opew
"""

import urllib.request
import datetime
import json

# client id, pw를 JSON 파일에서 읽어오기
def load_client_info(filename='naver_client.json'):
    with open(filename, 'r') as f:
        credentials = json.load(f)
    return credentials['client_id'], credentials['client_secret']

# 네이버 뉴스 API 호출 및 데이터 가져오기
def get_naver_search(client_id, client_secret, query, start=1, display=100, start_date=None, end_date=None):
    url = f"https://openapi.naver.com/v1/search/news.json?query={urllib.parse.quote(query)}&start={start}&display={display}"

    # 날짜 필터 추가
    if start_date and end_date:
        url += f"&startDate={start_date}&endDate={end_date}"

    req = urllib.request.Request(url)
    req.add_header("X-Naver-Client-Id", client_id)
    req.add_header("X-Naver-Client-Secret", client_secret)

    try:
        # API 요청 전송 및 응답 확인
        response = urllib.request.urlopen(req)
        if response.getcode() == 200:
            print(f"[{datetime.datetime.now()}] Url Request Success")
            return json.loads(response.read().decode('utf-8'))
    except Exception as e:
        # 오류
        print(e)
        print(f"[{datetime.datetime.now()}] Error for URL : {url}")
        return None

# 뉴스 데이터 추출 및 저장
def fetch_and_save_news(client_id, client_secret, region, month, year):
    query = f"{region} 축제"
    json_result = []
    start, cnt = 1, 0

    # 날짜 범위 설정
    start_date = f"{year}-{month:02d}-01"
    if month == 12:
        end_date = f"{year + 1}-01-01"
    else:
        end_date = f"{year}-{month + 1:02d}-01"

    while True:
        response = get_naver_search(client_id, client_secret, query, start, start_date=start_date, end_date=end_date)
        if response is None or response['display'] == 0:
            break  # 데이터가 없으면 반복 종료

        for post in response['items']:
            if cnt >= 500:  # 500개 저장
                break
            cnt += 1
            json_result.append({
                'cnt': cnt,
                'title': post['title'],
                'description': post['description']
            })

        start += response['display']

    # JSON 파일로 저장
    region_file_map = {
        "인천": "incheon",
        "서울": "seoul",
        "경기": "gyeonggi"
    }
    output_file = f"{region_file_map[region]}_{year}_{month}_news.json"
    with open(output_file, 'w', encoding='utf8') as outfile:
        json.dump(json_result, outfile, indent=4, ensure_ascii=False)
    print(f"{query} 크롤링 완료")

# 메인 함수
if __name__ == '__main__':
    client_id, client_secret = load_client_info()
    regions = ["인천", "서울", "경기"]
    year = 2024
    month = 1
    for region in regions:
        fetch_and_save_news(client_id, client_secret, region, month, year)